android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java

The RuntimeException, "Methods marked with @UiThread must be executed on the main thread", was introduced by https://github.com/flutter/engine/commit/2c9e37c34e79475bbde7c8163eb5e56cdb9662a1

Fix RuntimeException by sending replies on main thread

---

android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java
ios/Classes/AgoraRtcEnginePlugin.m

补充了native端result调用，去掉无意义的线程切换和条件判断

add native result call

---

README.md

docs. update readme

---

android/src/main/java/io/agora/agorartcengine/AgoraRenderViewFactory.java

CSD-12543：fix orientation bug

---

lib/src/agora_render_widget.dart

This solves https://github.com/AgoraIO/Flutter-SDK/issues/122

Key added for AgoraRenderWidget

---

CHANGELOG.md
android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraSurfaceViewFactory.kt
android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraTextureViewFactory.kt
example/android/app/src/main/AndroidManifest.xml
lib/src/rtc_render_view.dart
pubspec.yaml

fix https://github.com/AgoraIO/Flutter-SDK/issues/175

* fix android `VideoSizeChanged` bug

---

example/lib/examples/basic/join_channel_video.dart
lib/src/events.dart

Fixes type cast & invalid argument errors

---

README.jp.md

there are only English and Chinese documents. so I added.

Japanese document

---

README.md

Add link for Japanese document

---

example/lib/examples/advanced/MediaChannelRelay.dart
example/lib/examples/advanced/create_stream_data.dart
example/lib/examples/advanced/index.dart
example/lib/examples/advanced/live_streaming.dart
example/lib/examples/advanced/voice_change.dart
example/lib/examples/basic/join_channel_audio.dart
example/lib/examples/config/VoiceChangeConfig.dart
lib/src/rtc_channel.dart
lib/src/rtc_engine.dart

Bug fix and add example

---

android/build.gradle
example/android/app/src/test/kotlin/io/agora/agora_rtc_engine_example/FakeRtcEngine.kt
integration_test_app/integration_test/agora_rtc_engine_api_test.dart
integration_test_app/integration_test/agora_rtc_engine_event_handler_api_test.dart
lib/src/agora_media_recorder.dart
lib/src/api_types.dart
lib/src/classes.dart
lib/src/classes.g.dart
lib/src/enum_converter.dart
lib/src/enum_converter.g.dart
lib/src/enums.dart
lib/src/events.dart
lib/src/rtc_engine.dart
pubspec.yaml

Upgrade native sdk 3.5.2

---

lib/src/classes.dart
lib/src/enums.dart
lib/src/events.dart
lib/src/rtc_channel.dart
lib/src/rtc_device_manager.dart
lib/src/rtc_engine.dart
lib/src/rtc_engine_extension.dart
lib/src/rtc_render_view.dart

Update docs, pls help review @yamasite

feat: Update docs

---

README.md
README.zh.md

Hey team 👋
I've updated some formatting in the README file. Including removing some newlines, English structure, and badges to the top of both English and 中文 files.
Please let me know if these changes are okay.
Cheers!

README Updates

---

example/lib/config/agora.config.dart

Changed TEST_TOEKN to TEST_TOKEN 
As we are using the token getter it shouldn't break anything.

Fixed TYPO TEST_TOEKN ❌ to TEST_TOKEN ✔

---

example/example.md

The current example code on pub.dev doesn't build for 6.0 SDK. This is the updated code

The example code doesn't build

---

lib/src/impl/global_video_view_controller.dart

Need  wait for all `destroyTextureRender` functions are called completed before `FreeIrisVideoFrameBufferManager`, if not, the `destroyTextureRender`(call `IrisVideoFrameBufferManager.DisableVideoFrameBuffer` in native side) and `FreeIrisVideoFrameBufferManager` will be called parallelly, which will cause crash.

fix: fix crash of AgoraVideoView with flutter texture rendering

---

example/lib/examples/basic/join_channel_video/join_channel_video.dart
lib/src/impl/agora_video_view_impl.dart
lib/src/impl/media_player_controller_impl.dart
lib/src/impl/video_view_controller_impl.dart
lib/src/render/agora_video_view.dart
test_shard/integration_test_app/integration_test/testcases/agora_video_view_testcases.dart

Reland https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/962

Optimize initilizate time of AgoraVideoView

---

lib/src/agora_rtc_engine.dart
lib/src/binding/agora_rtc_engine_event_impl.dart
lib/src/binding/agora_rtc_engine_impl.dart
lib/src/binding/event_handler_param_json.dart
lib/src/binding/event_handler_param_json.g.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
tool/terra/terra_config_main.yaml

Fix function signature:
- `onFirstLocalVideoFrame `
- `numberOfCapabilities ` https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/959

fix some functions' signature

---

android/build.gradle
example/ios/Podfile
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.0.0.133.3 dependencies

feat: upgrade native sdk 4.0.0.133.3

---

lib/src/agora_base.dart
lib/src/agora_log.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_media_player_source.dart
lib/src/agora_media_player_types.dart
lib/src/agora_media_recorder.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_rtc_engine_ext.dart
lib/src/agora_spatial_audio.dart
lib/src/audio_device_manager.dart

[AUTO] Update doc 620
doc source: https://github.com/AgoraIO/agora_doc_source/releases/download/main/flutter_ng_json_template_en.json

[AUTO] Update doc 620

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20230525
```
```
```
打包助手 5-25 17:58 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.0-build.3/iris_4.2.0-build.3_DCG_iOS_Video_20230525_0544.zip Symbol: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.0-build.3/iris_4.2.0-build.3_DCG_iOS_Video_20230525_0544_symbols.zip CDN: https://download.agora.io/sdk/release/iris_4.2.0-build.3_DCG_iOS_Video_20230525_0544.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.2.0-build.3'  打包助手 5-25 18:03 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.0-build.3/iris_4.2.0-build.3_DCG_Windows_Video_20230525_0541.zip Symbol: …
```

feat: upgrade native sdk dependencies 20230525

---

android/build.gradle
example/lib/examples/basic/join_channel_video/join_channel_video.dart
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.1.0-build.2 dependencies

feat: upgrade native sdk 4.1.0-build.2

---

pubspec.yaml

Update native sdk 4.1.1.6-build.3 dependencies

feat: upgrade native sdk 4.1.1.6-build.3

---

.github/workflows/schedule-run-ci.yml

Fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/5241429159/jobs/9463512063

[ci][schedule-run-ci]Fix ReferenceError: labeled is not defined

---

lib/src/agora_base.dart
lib/src/agora_log.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_media_player_source.dart
lib/src/agora_media_player_types.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_rtc_engine_ext.dart
lib/src/agora_spatial_audio.dart
lib/src/audio_device_manager.dart
lib/src/render/agora_video_view.dart
lib/src/render/media_player_controller.dart
lib/src/render/video_view_controller.dart

[doc] daily update 2023-6-12

---

.cirrus.yml
.github/workflows/build.yml

CI failed due to this change
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/5281044699/jobs/9554068584?pr=1148
Reverts AgoraIO-Extensions/Agora-Flutter-SDK#1146

Revert "[ios] Run ios rendering test on github action runner"

---

lib/src/agora_rtc_engine.dart
lib/src/audio_device_manager.dart

[doc] daily update 2023-6-19

---

.github/workflows/build.yml

Reverts AgoraIO-Extensions/Agora-Flutter-SDK#1167

Revert "[ci][ios][rendering-test] Use github action to manipulate the ios simulator"

---

.github/workflows/build.yml

Reland the https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1176

Reland "Revert "[ci][ios][rendering-test] Use github action to manipulate the ios simulator (#1167)"" 

---

lib/src/agora_base.dart
lib/src/agora_log.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_media_player_source.dart
lib/src/agora_media_player_types.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_spatial_audio.dart
lib/src/audio_device_manager.dart
lib/src/impl/agora_video_view_impl.dart
lib/src/render/agora_video_view.dart
lib/src/render/media_player_controller.dart
lib/src/render/video_view_controller.dart

[AUTO] Update doc 422

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.2.2 dependencies

feat: upgrade native sdk 4.2.2 audio only

---

pubspec.yaml

Fix native resources leak, see https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/75

Update iris_method_channel: 1.2.1

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.1.1.13.MINI.VIDEO dependencies

feat: upgrade native sdk 4.1.1.13.MINI.VIDEO

---

pubspec.yaml

See https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/77

Upgrade iris_method_channel: 1.2.2

---

android/build.gradle
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_media_base.g.dart
lib/src/agora_media_engine.dart
lib/src/agora_music_content_center.dart
lib/src/agora_music_content_center.g.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine.g.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/binding/agora_rtc_engine_impl.dart
lib/src/binding/call_api_event_handler_buffer_ext.dart
lib/src/binding/event_handler_param_json.g.dart
lib/src/impl/video_view_controller_impl.dart
pubspec.yaml
scripts/artifacts_version.sh
test_shard/fake_test_app/integration_test/generated/mediaengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/musiccontentcenter_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
tool/terra/terra_config_main.yaml

Update native sdk 4.2.2.1 dependencies

feat: upgrade native sdk 4.2.2.1

---

example/lib/main.dart
lib/src/impl/platform/web/iris_web_rtc_bindings_js.dart
lib/src/impl/platform/web/js_iris_api_engine_binding_delegate.dart
pubspec.yaml

`iris_method_channel` changes: https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/84/files

[web] Optimize `callApi` logic

---

pubspec.yaml

See https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/86

Update iris_method_channel: 2.0.0-dev.3

---

lib/src/agora_base.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/audio_device_manager.dart

[AUTO] Update doc 423

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20231012
```
implementation 'io.agora.rtc:full-sdk:4.2.3' implementation 'io.agora.rtc:full-screen-sharing:4.2.3' pod 'AgoraRtcEngine_iOS', '4.2.3' pod 'AgoraRtcEngine_macOS', '4.2.3'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20231012/ios/iris_4.2.3-build.3_DCG_iOS_Video_20231012_0456.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20231012/ios/iris_4.2.3-build.3_DCG_iOS_Video_20231012_0456_private.zip CDN: https://download.agora.io/sdk/release/iris_4.2.3-build.3_DCG_iOS_Video_20231012_0456.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.2.3-build.3'  Iris: Artifactory: …
```

feat: upgrade native sdk dependencies 20231012

---

ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.0.0.133-build.2 dependencies

feat: upgrade native sdk 4.0.0.133-build.2

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.1.1.155 dependencies

feat: upgrade native sdk 4.1.1.155

---

scripts/iris_web_version.js

Update native sdk dependencies 20231023
```
```
```
CDN: https://download.agora.io/staging/iris-web-rtc-fake_0.1.2-dev.3.js  10-23 18:50 CDN: https://download.agora.io/staging/iris-web-rtc_0.1.2-dev.3.js
```

feat: upgrade native sdk dependencies 20231023

---

README.md
pubspec.yaml

- Enable web plugin config in `pubspec.yaml`
- Update `README.md` for how to integrate the `agora_rtc_engine` the on web

Enable web in pubspec.yaml and update README.md

---

lib/src/agora_base.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart

[doc] daily update 2023-10-29

---

tool/terra/.gitignore
tool/terra/.npmrc
tool/terra/build.sh
tool/terra/package.json
tool/terra/terra_config_main.yaml
tool/terra/tsconfig.json

Create a new npm module to use the new `terra` tool

[tool] Migrate to the new terra

---

example/lib/examples/basic/join_channel_audio/join_channel_audio.dart

Hide speakerphone relative example in the `JoinChannelAudio` case

[example][JoinChannelAudio] Hide speakerphone relative example

---

README.md
example/lib/examples/basic/join_channel_audio/join_channel_audio.dart
pubspec.yaml

Update native sdk n423_w4182_0.3.0 dependencies

feat: upgrade native sdk n423_w4182_0.3.0

---

.github/workflows/build.yml

Temporarily fix the sdkmanager tool installation issue https://github.com/actions/runner-images/issues/8761

[ci][build.yaml] Fix sdkmanager install failed in integration_test_android

---

android/src/main/java/io/agora/agora_rtc_ng/AgoraPlatformViewFactory.java

Fixes the use of `useAndroidSurfaceView`.

[fix] [android] Use SurfaceView instead of TextureView

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20231114
```
```
```
打包助手 11-14 15:49 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1/20231114/ios/iris_4.1.1.21-banban.1_DCG_iOS_Video_20231114_0339.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1/20231114/ios/iris_4.1.1.21-banban.1_DCG_iOS_Video_20231114_0339_private.zip CDN: https://download.agora.io/sdk/release/iris_4.1.1.21-banban.1_DCG_iOS_Video_20231114_0339.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.1.1.21-banban.1'  打包助手 11-14 15:50 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1/20231114/mac/iris_4.1.1.21-banban.1_DCG_Mac_Video_20231114_0339.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20231114

---

lib/src/agora_base.dart
lib/src/agora_log.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart

[doc] daily update 2023-11-23

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.1.1.21.a dependencies

feat: upgrade native sdk 4.1.1.21.a

---

macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk 4.2.6.1 dependencies

feat: upgrade native sdk 4.2.6.1

---

.github/workflows/build.yml
ci/rendering_test_ios.sh
test_shard/rendering_test/integration_test/common/screenshot_matcher_ext.dart
test_shard/rendering_test/ios/Runner/AppDelegate.swift

Bump the latest Flutter SDK version in build.yaml

[ci] Bump latest Flutter SDK version

---

pubspec.yaml

Update native sdk 4.1.1.21 dependencies

feat: upgrade native sdk 4.1.1.21

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20231208
```
```
```
打包助手 12-8 12:16 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20231208/ios/iris_4.3.0-dev.11_DCG_iOS_Video_20231208_1203.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20231208/ios/iris_4.3.0-dev.11_DCG_iOS_Video_20231208_1203_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.0-dev.11_DCG_iOS_Video_20231208_1203.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.3.0-dev.11'  打包助手 12-8 12:19 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20231208/android/iris_4.3.0-dev.11_DCG_Android_Video_20231208_1203.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20231208

---

README.md
android/src/main/AndroidManifest.xml

Cleanup some unused permissions following the 
https://docs.agora.io/en/video-calling/get-started/get-started-sdk?platform=android#project-setup

[android] Cleanup unused permissions settings

---

README.md
example/lib/examples/basic/join_channel_audio/join_channel_audio.dart
example/web/index.html
scripts/iris_web_version.js

update joinChannelAudio demo for flutter web

[flutter-web][demo]adapt iris_web 0.4.0

---

README.md
android/build.gradle
example/lib/examples/basic/join_channel_audio/join_channel_audio.dart
example/web/index.html
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/iris_web_version.js
test_shard/fake_test_app/integration_test/generated/basespatialaudioengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart

Update native sdk 6.2.6-sp.426.a dependencies

feat: upgrade native sdk 6.2.6-sp.426.a

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMusicContentCenter.h
android/src/main/cpp/third_party/include/iris/iris_base.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20231227
```
打包助手 12-27 11:45 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-dev.14'  打包助手 12-27 11:45 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-dev.14'  打包助手 12-27 11:45 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-dev.14'  打包助手 12-27 11:45 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-dev.14'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20231222/windows/iris_4.3.0-dev.14_DCG_Windows_Video_20231222_0659.zip Private: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20231222/windows/iris_4.3.0-dev.14_DCG_Windows_Video_20231222_0659_private.zip CDN: …
```

feat: upgrade native sdk dependencies 20231227

---

pubspec.yaml

Update packages: iris_method_channel, js, which make the score in pub.dev happy
https://pub.dev/packages/agora_rtc_engine/score

Update packages: iris_method_channel, js

---

android/build.gradle
ios/agora_rtc_engine.podspec
lib/src/impl/agora_media_engine_impl_override.dart
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk 4.2.6.4 dependencies

feat: upgrade native sdk 4.2.6.4

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240118
```
```
```
Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1.1.25/20240118/android/iris_4.1.1.25-sp.1_DCG_Android_Video_20240118_1208.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1.1.25/20240118/android/iris_4.1.1.25-sp.1_DCG_Android_Video_20240118_1208_private.zip CDN: https://download.agora.io/sdk/release/iris_4.1.1.25-sp.1_DCG_Android_Video_20240118_1208.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.1.1.25-sp.1' Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.1.1.25/20240118/ios/iris_4.1.1.25-sp.1_DCG_iOS_Video_20240118_1210.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20240118

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240123
```
打包助手 1-23 13:43 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-dev.20'  打包助手 1-23 13:43 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-dev.20'  打包助手 1-23 13:43 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-dev.20'  打包助手 1-23 13:43 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-dev.20'
```
```
打包助手 1-23 13:35 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240123/ios/iris_4.3.0-dev.20_DCG_iOS_Video_20240123_0127.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240123/ios/iris_4.3.0-dev.20_DCG_iOS_Video_20240123_0127_private.zip CDN: …
```

feat: upgrade native sdk dependencies 20240123

---

ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240124
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240124/mac/iris_4.3.0-test.3_DCG_Mac_Video_20240124_0131.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240124/mac/iris_4.3.0-test.3_DCG_Mac_Video_20240124_0131_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.0-test.3_DCG_Mac_Video_20240124_0131.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.3.0-test.3'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240124/windows/iris_4.3.0-test.3_DCG_Windows_Video_20240124_0130.zip Private: …
```

feat: upgrade native sdk dependencies 20240124

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240125
```
```
```
打包助手 1-25 11:58 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240125/ios/iris_4.3.0-test.5_DCG_iOS_Video_20240125_1146.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240125/ios/iris_4.3.0-test.5_DCG_iOS_Video_20240125_1146_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.0-test.5_DCG_iOS_Video_20240125_1146.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.3.0-test.5'  打包助手 1-25 11:58 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240125/mac/iris_4.3.0-test.5_DCG_Mac_Video_20240125_1146.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20240125

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240126
```
打包助手 1-26 11:56 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-dev.22'  打包助手 1-26 11:56 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-dev.22'  打包助手 1-26 11:56 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-dev.22'  打包助手 1-26 11:56 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-dev.22'
```
```
打包助手 1-26 11:50 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240126/mac/iris_4.3.0-dev.22_DCG_Mac_Video_20240126_1141.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240126/mac/iris_4.3.0-dev.22_DCG_Mac_Video_20240126_1141_private.zip CDN: …
```

feat: upgrade native sdk dependencies 20240126

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240131
```
```
```
打包助手 1-31 17:06 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.232/20240131/ios/iris_4.2.6.232-build.1_DCG_iOS_Video_20240131_0500.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.232/20240131/ios/iris_4.2.6.232-build.1_DCG_iOS_Video_20240131_0500_private.zip CDN: https://download.agora.io/sdk/release/iris_4.2.6.232-build.1_DCG_iOS_Video_20240131_0500.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.2.6.232-build.1'  打包助手 1-31 17:08 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.232/20240131/mac/iris_4.2.6.232-build.1_DCG_Mac_Video_20240131_0500.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20240131

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk 4.2.6.232 dependencies

feat: upgrade native sdk 4.2.6.232

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240219
```
打包助手 2-19 13:25 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-build.2'  打包助手 2-19 13:25 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-build.2'  打包助手 2-19 13:25 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-build.2'  打包助手 2-19 13:25 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-build.2'
```
```
Iris Windows: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240219/windows/iris_4.3.0-build.2_DCG_Windows_Video_20240219_0110.zip Private: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240219/windows/iris_4.3.0-build.2_DCG_Windows_Video_20240219_0110_private.zip CDN: …
```

feat: upgrade native sdk dependencies 20240219

---

.github/workflows/build.yml
ci/rendering_test_ios.sh

See https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1580

[ci] Disable rendering test agora_video_view_render_test.dart  on iOS

---

example/lib/examples/advanced/process_video_raw_data/process_video_raw_data.dart
example/pubspec.yaml
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.2.6.4-build.2 dependencies

feat: upgrade native sdk 4.2.6.4-build.2

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240313
```
打包助手 3-13 12:06 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.3'  打包助手 3-13 12:06 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.3'  打包助手 3-13 12:06 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.3'  打包助手 3-13 12:06 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.3'
```
```
Iris Windows: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240313/windows/iris_4.3.1-dev.3_DCG_Windows_Video_20240313_1152.zip Private: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240313/windows/iris_4.3.1-dev.3_DCG_Windows_Video_20240313_1152_private.zip CDN: …
```

feat: upgrade native sdk dependencies 20240313

---

.github/workflows/code-gen.yaml

Add action to run the `tool/terra` on CI

[ci] Add code-gen.yaml

---

.github/workflows/code-gen.yaml

Need more configurations to make it work.

[ci][code-gen.yaml] Fix run failed

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240318
```
打包助手 3-18 17:54 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.4'  打包助手 3-18 17:54 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.4'  打包助手 3-18 17:54 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.4'  打包助手 3-18 17:54 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.4'
```
```
Iris Windows: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240318/windows/iris_4.3.1-dev.4_DCG_Windows_Video_20240318_0530_378.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240318/windows/iris_4.3.1-dev.4_DCG_Windows_Video_Standalone_20240318_0530_378.zip Private: …
```

feat: upgrade native sdk dependencies 20240318

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240322
```
打包助手 3-21 18:31 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.7'  打包助手 3-21 18:31 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.7'  打包助手 3-21 18:31 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.7'  打包助手 3-21 18:31 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.7'  打包助手 3-21 18:31 CDN: https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_4.3.1-dev.7.zip
```
```
打包助手 3-21 18:22 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240321/ios/iris_4.3.1-dev.7_DCG_iOS_Video_20240321_0614_350.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240321/ios/iris_ …
```

feat: upgrade native sdk dependencies 20240322

---

android/build.gradle
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240326
```
打包助手 3-26 16:42 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.9'  打包助手 3-26 16:42 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.9'  打包助手 3-26 16:42 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.9'  打包助手 3-26 16:42 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.9'  打包助手 3-26 16:43 CDN: https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_4.3.1-dev.9.zip  打包助手 3-26 16:43 CDN: https://download.agora.io/sdk/release/AgoraRtcEngine_macOS_Preview_4.3.1-dev.9.zip
```
```
打包助手 3-26 16:37 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240326/ios/iris_4.3.1-dev.9_DCG_iOS_Video_Stan …
```

feat: upgrade native sdk dependencies 20240326

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.3.0.1 dependencies

feat: upgrade native sdk 4.3.0.1

---

android/build.gradle
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_media_base.g.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine.g.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/binding/agora_rtc_engine_event_impl.dart
lib/src/binding/agora_rtc_engine_impl.dart
lib/src/binding/call_api_event_handler_buffer_ext.dart
lib/src/binding/event_handler_param_json.dart
lib/src/binding/event_handler_param_json.g.dart
lib/src/impl/native_iris_api_engine_bindings.dart
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
tool/terra/.yarnrc.yml
tool/terra/package.json
tool/terra/terra_config_main.yaml
tool/terra/yarn.lock
windows/CMakeLists.txt

Update native sdk 4.1.1.28 dependencies

feat: upgrade native sdk 4.1.1.28

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.1.1.185 dependencies

feat: upgrade native sdk 4.1.1.185

---

android/build.gradle
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.2.6.8.MINI.VIDEO dependencies

feat: upgrade native sdk 4.2.6.8.MINI.VIDEO

---

android/build.gradle
android/src/main/cpp/third_party/include/iris/iris_rtc_rendering_c.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240410
```
打包助手 4-10 18:11 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.16'  打包助手 4-10 18:11 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.16'  打包助手 4-10 18:11 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.16'  打包助手 4-10 18:11 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.16'
```
```
打包助手 4-10 18:15 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240410/ios/iris_4.3.1-dev.16_DCG_iOS_Video_20240410_0607_378.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240410/ios/iris_4.3.1-dev.16_DCG_iOS_Video_Standalone_20240410_0607_378.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20240410

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240429
```
implementation 'io.agora.rtc:full-sdk:4.3.1' implementation 'io.agora.rtc:full-screen-sharing:4.3.1'  pod 'AgoraRtcEngine_iOS', '4.3.1' pod 'AgoraRtcEngine_macOS', '4.3.1'
```
```
Iris Android: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240429/android/iris_4.3.1-build.1_DCG_Android_Video_20240429_1017_481.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240429/android/iris_4.3.1-build.1_DCG_Android_Video_Standalone_20240429_1017_481.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240429/android/iris_4.3.1-build.1_DCG_Android_Video_20240429_1017_481_private.zip  CDN: …
```

feat: upgrade native sdk dependencies 20240429

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.1.1.29 dependencies

feat: upgrade native sdk 4.1.1.29

---

android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaEngine.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
internal/deps_summary.txt
scripts/artifacts_version.sh

Update native sdk dependencies 20240507
```
```
```
https://download.agora.io/sdk/release/iris_4.2.6.8-build.1_DCG_Android_Video_20240327_1207.zip https://download.agora.io/sdk/release/iris_4.2.6.8-build.1_DCG_iOS_Video_20240327_1207.zip pod 'AgoraIrisRTC_iOS', '4.2.6.8-build.1' implementation 'io.agora.rtc:iris-rtc:4.2.6.8-build.1'
```

feat: upgrade native sdk dependencies 20240507

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaEngine.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
lib/src/agora_media_engine.dart
lib/src/agora_music_content_center.dart
lib/src/agora_music_content_center.g.dart
lib/src/binding/agora_media_engine_impl.dart
lib/src/binding/agora_music_content_center_impl.dart
lib/src/impl/agora_music_content_center_impl_override.dart
pubspec.yaml
scripts/artifacts_version.sh
test_shard/fake_test_app/integration_test/generated/mediaengine_fake_test.generated.dart
tool/terra/.yarnrc.yml
tool/terra/package.json
tool/terra/terra_config_main.yaml

Update native sdk 4.2.6.8 dependencies

feat: upgrade native sdk 4.2.6.8

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaEngine.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMusicContentCenter.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240509
```
```
```
Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240509/ios/iris_4.2.6.10-build.1_DCG_iOS_Video_20240509_1139.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240509/ios/iris_4.2.6.10-build.1_DCG_iOS_Video_Standalone_20240509_1139.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240509/ios/iris_4.2.6.10-build.1_DCG_iOS_Video_20240509_1139_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.6.10-build.1_DCG_iOS_Video_20240509_1139.zip https://download.agora.io/sdk/release/iris_4.2.6.10-build.1_DCG_iOS_Video_Standalone_20240509_1139.zip Cocoapods: pod …
```

feat: upgrade native sdk dependencies 20240509

---

.github/workflows/build.yml
android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaEngine.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraMusicContentCenter.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
example/lib/examples/advanced/screen_sharing/screen_sharing.dart
example/macos/Runner.xcodeproj/project.pbxproj
example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine.g.dart
lib/src/agora_spatial_audio.dart
lib/src/impl/json_converters.dart
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
test/agora_media_base_test.dart
test/json_converters_test.dart
tool/terra/.yarnrc.yml
tool/terra/package.json
tool/terra/renderers/utils.ts
windows/CMakeLists.txt

Update native sdk 4.2.6.10 dependencies

feat: upgrade native sdk 4.2.6.10

---

example/lib/examples/advanced/screen_sharing/screen_sharing.dart
lib/src/impl/platform/web/global_video_view_controller_platform_web.dart
pubspec.yaml

Update native sdk 6.2.6-sp.42610.b.2 dependencies

feat: upgrade native sdk 6.2.6-sp.42610.b.2

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240531
```
```
```
Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.6_DCG_iOS_Video_Standalone_20240531_0442_407.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.6_DCG_iOS_Video_20240531_0442_407.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.6_DCG_iOS_Video_20240531_0442_407_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.3.2-dev.6_DCG_iOS_Video_Standalone_20240531_0442_407.zip https://download.agora.io/sdk/release/iris_4.3.2-dev.6_DCG_iOS_Video_20240531_0442_407.zip Cocoapods: pod 'AgoraIrisRTC_iOS', …
```

feat: upgrade native sdk dependencies 20240531

---

lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_media_base.g.dart
lib/src/agora_media_engine.dart
lib/src/agora_music_content_center.dart
lib/src/agora_music_content_center.g.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine.g.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/binding/agora_media_base_event_impl.dart
lib/src/binding/agora_media_engine_impl.dart
lib/src/binding/agora_music_content_center_impl.dart
lib/src/binding/agora_rtc_engine_event_impl.dart
lib/src/binding/agora_rtc_engine_ex_impl.dart
lib/src/binding/agora_rtc_engine_impl.dart
lib/src/binding/call_api_event_handler_buffer_ext.dart
lib/src/binding/call_api_impl_params_json.dart
lib/src/binding/call_api_impl_params_json.g.dart
lib/src/binding/event_handler_param_json.dart
lib/src/binding/event_handler_param_json.g.dart
test_shard/fake_test_app/integration_test/generated/event_ids_mapping_gen.dart
test_shard/fake_test_app/integration_test/generated/mediaengine_audioframeobserver_testcases.generated.dart
test_shard/fake_test_app/integration_test/generated/mediaengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_metadataobserver_testcases.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengineex_fake_test.generated.dart
tool/terra/terra_config_main.yaml

Update native sdk dependencies 20240612
```
```
```
```

feat: upgrade native sdk dependencies 20240612

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk dependencies 20240624
```
https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.14_25370_FULL_20240619_1843_313038.zip  【Cocoapods】 pod 'AgoraRtcEngine_Special_macOS', '4.2.6.14'  implementation 'io.agora.rtc:agora-special-full:4.2.6.14' implementation 'io.agora.rtc:full-screen-sharing:4.2.6.14'  pod 'AgoraRtcEngine_Special_iOS', '4.2.6.14'
```
```
打包助手 6-24 10:24 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240624/ios/iris_4.2.6.14-build.1_DCG_iOS_Video_Standalone_20240624_1016.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240624/ios/iris_4.2.6.14-build.1_DCG_iOS_Video_20240624_1016.zip PrivateArtifactory: …
```

feat: upgrade native sdk dependencies 20240624

---

lib/src/binding/agora_rtc_engine_impl.dart
lib/src/impl/agora_music_content_center_impl_override.dart
lib/src/impl/agora_rtc_engine_impl.dart
lib/src/impl/media_player_impl.dart
tool/terra/configs/cud_node_parser.config.ts
tool/terra/package.json
tool/terra/renderers/callapi_impl_renderer.ts
tool/terra/terra_config_main.yaml

After applying OverrideNodeParser, we can generate the redirect logic by terra.

[terra] Apply OverrideNodeParser

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_spatial_audio.dart
lib/src/binding/event_handler_param_json.g.dart
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
tool/terra/package.json
windows/CMakeLists.txt

Update native sdk 4.2.6.14 dependencies

feat: upgrade native sdk 4.2.6.14

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk 4.2.6.14-KK dependencies

feat: upgrade native sdk 4.2.6.14-KK

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.2.6.15.LITE dependencies

feat: upgrade native sdk 4.2.6.15.LITE

---

scripts/build-iris-ios.sh

Fix build-iris-ios.sh not work for the newest iris's changes.

[scripts] Fix build-iris-ios.sh not work

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_rtc_engine_ext.dart
lib/src/audio_device_manager.dart
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
tool/terra/package.json
windows/CMakeLists.txt

Update native sdk 4.2.6.15 dependencies

feat: upgrade native sdk 4.2.6.15

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml

Update native sdk 4.3.1.138 dependencies

feat: upgrade native sdk 4.3.1.138

---

example/android/app/src/main/kotlin/io/agora/agora_rtc_flutter_example/MyApplication.kt

Close https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1942

[example] Remove references to deprecated v1 Android embedding

---

example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/kotlin/io/agora/agora_rtc_flutter_example/ExampleService.kt
example/lib/main.dart

Adapt foreground service changes on Android 14.
https://developer.android.com/about/versions/14/changes/fgs-types-required
Fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1783

[example] Fix crash when run on Android 14

---

.github/workflows/build.yml
example/pubspec.yaml
pubspec.yaml
test_shard/fake_test_app/pubspec.yaml
test_shard/integration_test_app/pubspec.yaml
test_shard/iris_tester/pubspec.yaml
test_shard/rendering_test/pubspec.yaml

Bump minimum supported Flutter SDK >= 3.0.0 to reduce the maintenance cost.

feat: Bump minimum supported Flutter SDK >= 3.0.0

---

tool/terra/terra_config_main.yaml

See https://github.com/AgoraIO-Extensions/terra_shared_configs/pull/144

[tool/terra] Update the path of custom_headers

---

lib/src/agora_base.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/agora_rtc_engine_ext.dart
lib/src/audio_device_manager.dart
lib/src/impl/platform/io/native_iris_api_engine_bindings.dart

[doc] daily update 2024-9-24

---

lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine.g.dart
lib/src/binding/agora_rtc_engine_impl.dart
lib/src/binding/call_api_impl_params_json.dart
lib/src/binding/call_api_impl_params_json.g.dart
lib/src/binding/event_handler_param_json.g.dart
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
test_shard/fake_test_app/integration_test/generated/rtcengineex_fake_test.generated.dart

Update native dependencies 20240929
```
```

feat: upgrade native sdk dependencies 20240929

---

android/build.gradle

This pull request addresses the error `com.android.builder.errors.EvalIssueException: [CXX1110] Platform version 16 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.` by increasing the minSdkVersion from 16 to 21.
```
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] A problem occurred configuring project ':agora_rtc_engine'.
[        ] > com.android.builder.errors.EvalIssueException: [CXX1110] Platform version 16 is unsupported by this NDK. Please change minSdk to at least 21 to avoid …
```

fix: Update minSdkVersion to 21 to Fix NDK Compatibility Issue

---

example/android/app/build.gradle
test_shard/fake_test_app/android/app/build.gradle
test_shard/integration_test_app/android/app/build.gradle
test_shard/iris_tester/android/build.gradle
test_shard/rendering_test/android/app/build.gradle

Fix CI failed after https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1832 merged.
Failed jobs https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/11288828373/job/31397409526?pr=2043

[ci] Fix CI failed after bumping minSdkVersion to 21

---

.github/workflows/build.yml

Fix failed job: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/11342411219/job/31542828499?pr=2036

[ci] Bump jdk version 17

---

android/build.gradle
android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_player.h
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
lib/src/agora_base.dart
lib/src/agora_base.g.dart
lib/src/agora_media_base.dart
lib/src/agora_media_engine.dart
lib/src/agora_media_player_source.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
macos/agora_rtc_engine.podspec
scripts/artifacts_version.sh
test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
tool/terra/package.json
windows/CMakeLists.txt

Update native dependencies 20241028
```
打包助手 10-28 16:40 Iris macOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241028/mac/iris_4.5.0-dev.10_DCG_Mac_Video_Standalone_20241028_0432_518.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241028/mac/iris_4.5.0-dev.10_DCG_Mac_Video_20241028_0432_518.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241028/mac/iris_4.5.0-dev.10_DCG_Mac_Video_20241028_0432_518_xdump.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241028/mac/iris_4.5.0-dev.10_DCG_Mac_Video_20241028_0432_518_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.5.0-dev.10_DCG_Mac_Video_Standalone_20241028_0432_518.zip …
```

feat: upgrade native sdk dependencies 20241028

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.2.6.248-build.2 dependencies

feat: upgrade native sdk 4.2.6.248-build.2

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
macos/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh
windows/CMakeLists.txt

Update native sdk 4.2.6.147 dependencies

feat: upgrade native sdk 4.2.6.147

---

lib/src/agora_base.dart
lib/src/agora_media_base.dart
lib/src/agora_media_player.dart
lib/src/agora_media_player_source.dart
lib/src/agora_media_player_types.dart
lib/src/agora_rtc_engine.dart
lib/src/agora_rtc_engine_ex.dart
lib/src/audio_device_manager.dart

[AUTO] Update doc

---

.github/workflows/prepare-release.yml
.github/workflows/release.yml
.github/workflows/release_special_version.yml

See https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/111

[ci] Fix CI failed caused by using an unsupported NodeJS version

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.4.0 dependencies

feat: upgrade native audio sdk 4.4.0

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.5.0 dependencies

feat: upgrade native sdk 4.5.0

---

android/build.gradle
internal/deps_summary.txt
ios/agora_rtc_engine.podspec
pubspec.yaml
scripts/artifacts_version.sh

Update native sdk 4.3.2.236 dependencies

feat: upgrade native sdk 4.3.2.236

---

.github/workflows/run_prepare_release.yml
.github/workflows/run_pub.yml

pick commit https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/commit/308ae49dfb33da4052dc14365db0e46bd6840dcc and https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/commit/86cd63109d2059f1d847e837cb9079be36ef4e4b

chore: fix issue in prepare release action and run pub action
