- android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java
- example/lib/main.dart
- example/pubspec.yaml
- lib/agora_rtc_engine.dart
- lib/src/agora_render_widget.dart
如题，设计了一个简单的渲染窗口控件，简化渲染窗口widget的构建，使其更符合flutter UI构建习惯。
> 简化了原生渲染窗口的创建接口，增加了一个实用渲染窗口控件

- android/build.gradle
- android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java
- ios/Classes/AgoraRtcEnginePlugin.m
- lib/agora_rtc_engine.dart
目的：主要是针对 #23 提到的问题进行修复，新增了对[语音变声效果](https://docs.agora.io/cn/Audio%20Broadcast/voice_effect_android_audio?platform=Android)的支持。
做法：根据SDK预设的6个选项，新增了枚举类型：
```dart
enum VoiceChanger {
/// The original voice (no local voice change).
VOICE_CHANGER_OFF,
/// An old man's voice.
VOICE_CHANGER_OLDMAN,
/// A little boy's voice.
VOICE_CHANGER_BABYBOY,
///A little girl's voice.
VOICE_CHANGER_BABYGILR,
/// Zhu Bajie's voice (Zhu Bajie is a character from Journey to the West who has a voice like a growling bear).
VOICE_CHANGER_ZHUBAJIE,
/// Ethereal vocal effects.
VOICE_CHANGER_ETHEREAL,
/// Hulk's voice.
VOICE_CHANGER_HULK
}
```
并在**invokeMethod方法**转换为[整形参数](https://docs.agora.io/cn/Audio%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ade6883c7878b7a596d5b2563462597dd)。 …
> feat. support setLocalVoiceChanger

- README.md
参考[Flutter Plugins](https://github.com/flutter/plugins)，都添加了动态更新的徽章图标，以帮助开发迅速拉取最新Package，而不需要到[Dart Pub](https://pub.dev/packages/agora_rtc_engine)去寻找。
> 新增Pub仓库徽章，以便于迅速拉取最新版本

- android/build.gradle
- example/.gitignore
- example/android/app/build.gradle
升级到[Android X](https://developer.android.com/jetpack/androidx)后，**compileSdkVersion**的最低为28，否则无法构建出apk。
> upgrade compileSdkVersion and fix #46, #52, #53

- example/example.md
In example, `RtcRemoteView.SurfaceView` missed a named parameter `channelId`
> fix: Add missing named parameter 'channelId' for SurfaceView in example

- README.md
- badges.bar is no more, using shields for badges - ([#27](https://github.com/bruno-garcia/badges.bar/issues/27))
> Swap out Readme Badges

- .github/workflows/pubdev.yml
- Deploy to pub.dev on new release creation. Relevant tokens have been added to the organisation and exposed to this repo.
> Based on the [VideoUIKit-Flutter deployment script](https://github.com/AgoraIO-Community/VideoUIKit-Flutter/actions/runs/3136447317/jobs/5093370342).
@LichKing-2234 @littleGnAl please give any feedback on this or ask any questions if anything's unclear.
The objective is to make deployment easier, and have GitHub as the source of truth for this package and its versions.
> Deploy to pub.dev

- .github/workflows/pubdev.yml
We want to use the tag to manage the special version and dev version, but we only want to publish a stable and pre-release version to pub.dev, so we strictly match the tag version here.
> [action][pubdev] Only publish if stable or pre-release

- .cirrus.yml
- .github/workflows/rendering_test.yml
- test_shard/rendering_test/integration_test/agora_video_view_render_test.dart
After Ventura, we notice that the flutter texture can be worked on the iOS simulator, but the GitHub action runner still [does not support the macos-13](https://github.com/actions/runner-images/issues/6426) at this time, but cirrus ci does, so we try to move the iOS rendering test to cirrus ci.
> [iOS] Move rendering test to cirrus ci

- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
After the cirrus ci update the Android toolchain `Platform android-33, build-tools 33.0.1` of `ghcr.io/cirruslabs/macos-ventura-xcode:14` caused the build to fail.
see https://github.com/cirruslabs/macos-image-templates/commit/9b63d54a046bfe49ce2aede918680d8f8dc3feea
see fail https://cirrus-ci.com/task/4709914724007936
Upgrade the AGP 7.1.2 to fix it.
> [example] fix Android build on macos m1

- lib/src/impl/agora_rtc_engine_impl.dart
- lib/src/impl/native_iris_api_engine_binding_delegate.dart
- pubspec.yaml
Update iris_method_channel: 1.1.0-rc.2 to fix hot restart issue, see PR https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/9
> fix: fix hot restart not work

- pubspec.yaml
Update `iris_method_channel` to 1.1.0-rc.3 to fix _HotRestartFinalizer._onExitPort not be initialized in release build
see fix https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/34
> fix: fix _HotRestartFinalizer._onExitPort not be initialized in release build

- .github/workflows/build.yml
- example/ios/Podfile
Disable the bitcode in ios example since:
* After xcode 14, bitcode is removed
* The native sdk 4.1.1.x and later version have disabled the bitcode by default.
> [example][ios] disable bitcode

- lib/src/impl/agora_rtc_engine_impl.dart
We listen to the `WidgetsBindingObserver.didChangeAppLifecycleState` in `RtcEngine.initialize`, and when the `AppLifecycleState.detached` is triggered, we call `RtcEngine.release` to clean up the `RtcEngine`.
In Android
For the standalone Flutter APP, the `AppLifecycleState.detached` is triggered when `FlutterActivity.onDestroy` is called, the APP is closed at this time.
But in add2app scenario, the `AppLifecycleState.detached` is triggered when the `FlutterActivity` finish, the APP is not closed at this time, e.g., the user just detaches the `FlutterEngine` from the `FlutterActivity`, so we should not call `RtcEngine.release` at this time.
Since after migrating to `iris_method_channel`, the `RtcEngine` can be clean up correctly, so it's ok to remove the listener.
> fix: fix RtcEngine.release be called due to inaccurate app lifecycle callback in add2app scenario

- windows/texture_render.cc
The call to `Dispose` in the `TextureRender` destructor is unnecessary, and may cause unexpected behavior, so remove it.
> [windows] remove Dispose in TextureRender destructor

- example/lib/examples/basic/join_channel_video/join_channel_video.dart
- lib/src/impl/agora_video_view_impl.dart
- lib/src/impl/media_player_controller_impl.dart
- lib/src/impl/video_view_controller_impl.dart
- lib/src/render/agora_video_view.dart
1. Create flutter Platform View when `AgoraVideoView` is created, reduce the time spent on the `RtcEngine.setupLocalVideo` flow: create flutter Platform View -> `RtcEngine.setupLocalVideo`
2. Add `onAgoraVideoViewCreated ` callback to indicate that the `AgoraVideoView` created
> Optimize initilizate time of AgoraVideoView with PlatformView rendering

- pubspec.yaml
Upgrade the `iris_method_channel: ^1.1.0-rc.5` to fix the crash caused by the memory leak.
See https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/42
> fix: fix crash caused by memory leak when register the raw data observers

- .github/workflows/release.yml
- .github/workflows/release_special_version.yml
If the PR with the label `ci:ready_release_special` is merged, this action will be triggered to tag a special version.
> [ci] add action to tag the special version after PR merged

- windows/include/agora_rtc_engine/texture_render.h
- windows/texture_render.cc
- windows/video_view_controller.cc
The `TextureRender` is not thread safe when destruct, if the Flutter texture is still processing. 
Say that if `registrar_->MarkTextureFrameAvailable(texture_id_);` is triggered inside the `OnVideoFrameReceived` and the `destroyTextureRender` is called from MethodChannel immediately, the `TextureRender` is erased from the map which will cause the `TextureRender`  desctruct, so if the `CopyPixelBuffer` is triggered by Flutter at this time, it will crash.
Borrow the implementation from https://github.com/flutter/packages/blob/main/packages/camera/camera_windows/windows/texture_handler.cpp
to implementation the `FlutterDesktopPixelBuffer::release_callback` and `FlutterDesktopPixelBuffer::release_context` to guarantee the thread safe.
> fix: [windows] fix AgoraVideoView dispose crash due to multithreading

- lib/src/impl/media_player_controller_impl.dart
- lib/src/impl/video_view_controller_impl.dart
The `MediaPlayerController` is `initialize`/`dispose` by the user, so we can reuse the same `MediaPlayerController` for the `AgoraVieoView` when an existing `AgoraVieoView` is disposed, and then a new `AgoraVieoView` to be rendered, to new `AgoraVieoView` can not be shown, due to the incorrect value of `_isCreatedRender `, `_isDisposeRender `
> fix the new AgoraVieoView not be shown when reuse the same MediaPlayerController

- lib/src/impl/agora_video_view_impl.dart
Align the native sdk mirror logic, we should not mirror the screen-sharing source type.
> fix: should not mirror the screen sharing

- lib/src/impl/agora_rtc_engine_impl.dart
`startDirectCdnStreaming ` is called through `IrisMethodChannel.registerEventHandler`, but isn't called `IrisMethodChannel.unregisterEventHandler` in `stopDirectCdnStreaming `, it cause the `startDirectCdnStreaming` can not be called again although `stopDirectCdnStreaming` is called.
> fix: can not call startDirectCdnStreaming again after stopDirectCdnStreaming

- example/lib/components/basic_video_configuration_widget.dart
- example/lib/examples/advanced/screen_sharing/screen_sharing.dart
- example/lib/examples/basic/join_channel_video/join_channel_video.dart
Add `BasicVideoConfigurationWidget` widget that reuses the basic video config, `width`, `height`, `frameRate`, etc.
> [example] Add BasicVideoConfigurationWidget widget

- pubspec.yaml
The [iris_method_channel](https://pub.dev/packages/iris_method_channel/versions/1.1.0) had released version 1.1.0 but with a breaking change, but the `agora_rtc_engine` dependent it with caret-syntax `^`, so the `iris_method_channel` will be upgraded automatically when run `flutter packages get`, set a fixed version to avoid this. And the `iris_method_channel` should increase the major or minor version num if there're breaking changes in the future.
> fix: Fix build error due to iris_method_channel break change

- .cirrus.yml
Not sure why, but the integration test keeps failing due to an invalid app id, it seems the encrypted app id is invalid, try renewing one.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1090/checks?check_run_id=13599709395
> [ci][cirrus] Renew TEST_APP_ID

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230525
```
implementation 'io.agora.rtc:full-screen-sharing:4.2.0'  implementation 'io.agora.rtc:full-sdk:4.2.0'   pod 'AgoraRtcEngine_iOS', '4.2.0'  pod 'AgoraRtcEngine_macOS', '4.2.0' 
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.0-build.2/iris_4.2.0-build.2_DCG_Windows_Video_20230524_0304.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.0-build.2_DCG_Windows_Video_20230524_0304.zip  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.0-build.2/iris_4.2.0-build.2_DCG_Mac_Video_20230524_0307.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.0-build.2_DCG_Mac_Video_20230524_0307.zip Cocoapods: …
```
> feat: upgrade native sdk dependencies 20230525

- lib/src/impl/agora_rtc_engine_impl.dart
- test_shard/integration_test_app/integration_test/testcases/rtcengine_smoke_test_testcases.dart
Currently, if call the `RtcEngine.release` directly, but do not call `RtcEngine.initialize`, it will throw an error, this should be a bug. This PR let the `RtcEngine.release` as a no-op if do not call `RtcEngine.initialize` ever.
> fix: no-op if call RtcEngine.release without calling RtcEngine.initialize directly

- .github/workflows/schedule-run-ci.yml
The label: "ci:schedule_run_ci" is added automatically for internal contributors, which will trigger the action="labeled" when the label is added, skip the action="labeled" to avoid schedule run ci multiple times.
> [ci][schedule-run-ci] Avoid trigger the ci run for internal contributors when action is labeled

- lib/src/impl/agora_video_view_impl.dart
- lib/src/impl/video_view_controller_impl.dart
- test_shard/integration_test_app/integration_test/testcases/agora_video_view_testcases.dart
In platform view rendering, we call "getNativeViewPtr" through the method channel, which is an async call, it's a potential crash that we may get an invalid view ptr, if the widget is disposed before the call is completed. Add a disposal check when setup the native view.
May fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1131.
> fix: do not setup native view if the widget is disposed in platform view rendering

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230615
```
implementation 'io.agora.rtc:agora-full-preview:4.2.2-dev.2'  implementation 'io.agora.rtc:full-screen-sharing-special:4.2.2-dev.2' pod 'AgoraRtcEngine_macOS_Preview', '4.2.2-dev.2' pod 'AgoraRtcEngine_iOS_Preview', '4.2.2-dev.2'
```
```
Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-dev.4/iris_4.2.2-dev.4_DCG_Windows_Video_20230615_1046.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.2-dev.4_DCG_Windows_Video_20230615_1046.zip   Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-dev.4/iris_4.2.2-dev.4_DCG_iOS_Video_20230614_0816.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.2-dev.4_DCG_iO …
```
> feat: upgrade native sdk dependencies 20230615

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230621
```
implementation 'io.agora.rtc:agora-full-preview:4.2.1-dev.2' Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.2.1-dev.2' Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.2.1-dev.2' Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.2.1-dev.2'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.1-dev.2/iris_4.2.1-dev.2_DCG_Mac_Video_20230620_0413.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.1-dev.2_DCG_Mac_Video_20230620_0413.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.2.1-dev.2'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.1-dev.2/iris_4.2.1-dev.2_DCG_Windows_Video_2023 …
```
> feat: upgrade native sdk dependencies 20230621

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230625
```
implementation 'io.agora.rtc:full-sdk:4.2.1'  implementation 'io.agora.rtc:full-screen-sharing:4.2.1'  [Cocoapods] iOS: full: pod 'AgoraRtcEngine_iOS', '4.2.1'  Mac: full: pod 'AgoraRtcEngine_macOS', '4.2.1'  
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.1-build.1/iris_4.2.1-build.1_DCG_Mac_Video_20230625_1129.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.1-build.1_DCG_Mac_Video_20230625_1129.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.2.1-build.1'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.1-build.1/iris_4.2.1-build.1_DCG_Windows_Video_20230625_1112.zip  CDN: …
```
> feat: upgrade native sdk dependencies 20230625

- ci/rendering_test_ios.sh
- lib/src/impl/video_view_controller_impl.dart
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
fix: Fix `AgoraVideoView` not showing correctly when resued the same `VideoViewController`.
When reusing the same `VideoViewController`, and create/dispose of the `AgoraVideoView` multiple times, the `VideoViewControllerBaseMixin._isDisposeRender ` flag is not reset correctly in the `setupView`, which causes the `disposeRender ` not to be called.
It's better to use state management for the `AgoraVideoView` in the future, at this time, just fix the bug first.
> fix: Fix AgoraVideoView not showing correctly when reusing the same VideoViewController

- lib/src/impl/agora_video_view_impl.dart
- lib/src/impl/video_view_controller_impl.dart
- lib/src/render/video_view_controller.dart
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
When the `AgoraVideoView`s are reused, say that the parent widget call `setState` many times(trigger `build` function), 
the `VideoViewController` with the same config (`VideoCanvas`, `RtcConntection`, ...) does not keep updated to date.
Add a new function `VideoViewControllerBaseMixin.updateController ` to update the states from the old `VideoViewController` in the `State.didUpdateWidget`.
> fix: Fix VideoViewController state not correct when the AgoraVideoViews are reused

- .github/workflows/build.yml
- ci/rendering_test_ios.sh
It's so weird that the ios rendering test failed https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1166 after this change https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/commit/8b2436cc0209baa0c39e175f8f4b7caf9138cbd1, add more log to see what's happening.
> [ci][ios][rendering-test] Use github action to manipulate the ios simulator

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230704
```
implementation 'io.agora.rtc:agora-full-preview:4.2.2-dev.5'  Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.2.2-dev.5'  Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.2.2-dev.5'  Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.2.2-dev.5'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-dev.6/iris_4.2.2-dev.6_DCG_Android_Video_20230704_0337.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.2-dev.6_DCG_Android_Video_20230704_0337.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.2.2-dev.6'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-dev.6/iris_4.2.2-dev.6_DCG_ …
```
> feat: upgrade native sdk dependencies 20230704

- example/lib/examples/advanced/media_recorder/media_recorder.dart
- lib/src/impl/agora_media_recorder_impl_override.dart
- lib/src/impl/agora_rtc_engine_impl.dart
- test_shard/integration_test_app/integration_test/fake_apis_call_integration_test.dart
- test_shard/integration_test_app/integration_test/testcases/mediarecorder_fake_test_testcases.dart
`RtcEngine.destroyMediaRecorder` does not trigger `MediaRecorderImpl.dispose`, causing the newly created `MediaRecorder`'s `setMediaRecorderObserver` not to be called, causing the newly created `MediaRecorder`'s `startRecording` return -4.
Issue https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1190
> fix: Fix MediaRecorder.startRecording return -4 after the previous destroy

- lib/src/impl/agora_rtc_engine_impl.dart
After upgrading the native sdk 4.2.0, iris fixed the iris log path that can not be set when initialization in Android. So it's not necessary to call the `setLogFile ` inside the `RtcEngine.initialize` again, or it cause the incorrect log file path.
> fix: [android] Fix reset the log file in RtcEngine.initialize cause incorrect log file path

- .cirrus.yml
- .github/workflows/build.yml
After moving the ios rendering test to github action runner period of time, we notice that the ios rendering test on github action runner is unstable. I am not sure if it causes by the `macos-13` not yet being stable or not. To avoid the CI block we process the test, we decide to move back the ios rendering test to cirrus ci at this time.
And only build the android with the min and latest flutter sdk on macOS VM to reduce the build time in cirrus ci.
> [ci] Move back ios rendering test to cirrus ci

- .github/workflows/schedule-run-ci-external.yml
- .github/workflows/schedule-run-ci-internal.yml
This PR fixes the following errors:
1. The `schedule-run-ci-internal` had run for external contributors
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/5517948306/jobs/10061924087?pr=1205
2. The `schedule-run-ci-external` throw exception when checking the user status
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/5518328576/jobs/10062123801?pr=1205
> [ci] Fix schedule-run-ci* not work as expected for external contributors

- lib/src/agora_base.dart
- lib/src/agora_base.g.dart
- lib/src/binding/event_handler_param_json.g.dart
Add 5G to available network types on Dart side to fix the argument error when method channel returns 6 from native side which corresponds to 5G.
> fix: Add missing `NetworkType.networkTypeMobile5g`

- android/src/main/java/io/agora/agora_rtc_ng/AgoraPlatformViewFactory.java
- android/src/main/java/io/agora/agora_rtc_ng/AgoraRtcNgPlugin.java
- android/src/main/java/io/agora/agora_rtc_ng/VideoViewController.java
- ci/run_flutter_integration_test_android.sh
- ci/run_flutter_integration_test_ios.sh
- ios/Classes/AgoraRtcNgPlugin.m
- ios/Classes/AgoraSurfaceViewFactory.h
- ios/Classes/AgoraSurfaceViewFactory.mm
- ios/agora_rtc_engine.podspec
- lib/src/impl/agora_rtc_engine_impl.dart
- lib/src/impl/agora_video_view_impl.dart
- lib/src/impl/global_video_view_controller.dart
- lib/src/impl/video_view_controller_impl.dart
- pubspec.yaml
- shared/darwin/VideoViewController.h
- shared/darwin/VideoViewController.mm
- test_shard/integration_test_app/integration_test/apis_call_integration_test.dart
- test_shard/integration_test_app/integration_test/fake/fake_iris_method_channel.dart
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
Summary for this issue:
All the call in `agora_rtc_engine` is async. For the `setupLocalVideo/setupRemoteVideo` function, we need to keep native views(`SurfaceView/TextureView` in Android, `UIView` in iOS) reference in PlatformView as long as the async call, or it will be crashed.
More detail:
At this time we pass the int ptr of the native views(`SurfaceView/TextureView` in Android, `UIView` in iOS) to Flutter side, and call the `setupLocalVideo/setupRemoteVideo` of the native sdk via ffi through the `IrisMethodChannel`. The call of `IrisMethodChannel` run in the standalone isolate, which is an async call, it's unsafe to direct access the int ptr of the `UIView` without adding additional reference.
The flow in iOS below will crash(similar in Android):
```
AgoraVideoView  AgoraSurfaceView …
```
> fix: Fix ios crash due to AgoraVideoView.dipose call before RtcEngine.setupxxVideo

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230727
```
implementation 'io.agora.rtc:full-sdk:4.2.2' implementation 'io.agora.rtc:full-screen-sharing:4.2.2' pod 'AgoraRtcEngine_iOS', '4.2.2' pod 'AgoraRtcEngine_macOS', '4.2.2'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-build.1/iris_4.2.2-build.1_DCG_Mac_Video_20230727_1159.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.2-build.1_DCG_Mac_Video_20230727_1159.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.2.2-build.1'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2-build.1/iris_4.2.2-build.1_DCG_Android_Video_20230727_1158.zip CDN: …
```
> feat: upgrade native sdk dependencies 20230727

- lib/src/impl/video_view_controller_impl.dart
We call `VideoViewControllerBaseMixin.setupView ` after`onPlatformViewCreated` callback is called, and the `didUpdateWidget`(which trigger `VideoViewControllerBaseMixin.updateController `) may be called before the `VideoViewControllerBaseMixin.setupView `, which may cause the in-correct `_isCreatedRender `/`_isDisposeRender ` value are set.
This PR removes the state(`_isCreatedRender `/`_isDisposeRender `) in the `VideoViewControllerBaseMixin`, and the `VideoViewControllerBaseMixin` should no longer maintain the state to avoid the unexpected issue.
> fix: Fix VideoViewControllerBaseMixin state in-correct issue

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230811
```
【cdn】 https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.1.1.147_21486_FULL_20230810_1825_274401.zip  https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_rel.v4.1.1.147_66276_FULL_20230810_1748_274396.zip  https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_rel.v4.1.1.147_52197_FULL_20230810_1745_274392.zip  【maven】 implementation 'io.agora.rtc:full-screen-sharing:4.1.1.147'  implementation 'io.agora.rtc:agora-special-full:4.1.1.147'  【cocopods】 pod 'AgoraRtcEngine_Special_iOS', '4.1.1.147' 
```
```
CDN: https://download.agora.io/sdk/release/iris_4.1.1.147-build.3_DCG_iOS_Video_20230811_0336.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.1.1.147-build.3' …
```
> feat: upgrade native sdk dependencies 20230811

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230815
```
```
```
Iris: Artifactory: CDN: https://download.agora.io/sdk/release/iris_4.1.1.147-build.4_DCG_iOS_Video_20230815_0248.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.1.1.147-build.4'  Iris: CDN: https://download.agora.io/sdk/release/iris_4.1.1.147-build.4_DCG_Mac_Video_20230815_0248.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.1.1.147-build.4'  Iris: CDN: https://download.agora.io/sdk/release/iris_4.1.1.147-build.4_DCG_Windows_Video_20230815_0248.zip  Iris: CDN: https://download.agora.io/sdk/release/iris_4.1.1.147-build.4_DCG_Android_Video_20230815_0248.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.1.1.147-build.4'
```
> feat: upgrade native sdk dependencies 20230815

- android/build.gradle
- ios/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
Update native sdk dependencies 20230906
```
【maven】 implementation 'io.agora.rtc:full-screen-sharing:4.2.2.1' implementation 'io.agora.rtc:agora-special-full:4.2.2.1'  pod 'AgoraRtcEngine_Special_iOS', '4.2.2.1'
```
```
Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.2.1-build.2_DCG_Android_Video_20230906_1234.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.2.2.1-build.2'  Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.2.1-build.2_DCG_iOS_Video_20230906_1234.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.2.2.1-build.2'
```
> feat: upgrade native sdk dependencies 20230906

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230912
```
Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.2.3-dev.2' Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.2.3-dev.2' Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.2.3-dev.2' Packages: implementation 'io.agora.rtc:agora-full-preview:4.2.3-dev.2'
```
```
Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.3-dev.2_DCG_Windows_Video_20230911_0458.zip  Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.3-dev.2_DCG_Mac_Video_20230911_0458.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.2.3-dev.2'  Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.3-dev.2_DCG_Android_Video_20230911_0458.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.2.3-dev.2'  Iris: CDN: …
```
> feat: upgrade native sdk dependencies 20230912

- windows/video_view_controller.cc
There're customers report that the `irisRtcRenderingHandle` maybe in 32-bit, need to use `EncodableValue.LongValue` to cast the value to `int64_t` explictly.
> fix: [windows] Fix can not get `irisRtcRenderingHandle` in 32-bit

- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20230913
```
```
```
Iris: CDN: https://download.agora.io/sdk/release/iris_4.2.3-dev.4_DCG_Windows_Video_20230912_0614.zip
```
> feat: upgrade native sdk dependencies 20230913

- lib/src/agora_rtc_engine_ext.dart
- lib/src/impl/agora_rtc_engine_impl.dart
Make the `getAssetAbsolutePath` function work on web.
> [web] Compatible getAssetAbsolutePath function on web

- .github/workflows/ triage-agora-support.yaml
Add github action to add triage to Agora Support comment by bot for the issues.
> [ci] Add request to triage to Agora Support action

- .github/workflows/more-detail-wanted.yaml
Add an action to request more details of the issue by the github action bot.
When labeling the "more detail wanted", the bot will comment with the following message:
```
Please follow the [issue template](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to fill in more details about this issue so that we can investigate this issue more easily, thanks!
```
> [ci] Add more-detial-wanted.yaml action

- .github/workflows/build.yml
- .github/workflows/release.yml
- lib/src/impl/platform/io/native_iris_api_engine_bindings.dart
- test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
- test_shard/iris_tester/lib/src/iris_tester_bindings.dart
- test_shard/rendering_test/test_driver/integration_test.dart
- add `dart format` to build process
- upload zipped dartdoc on release
> Formatter Check and DartDoc Upload

- .github/workflows/schedule-run-ci-internal.yml
Add `ci:skip` label check in `schedule-run-ci-internal.yaml` to avoid adding the label check in each step in `build.yaml`.
> [ci][schedule-run-ci-internal] Add skip ci check

- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
The `CFBundleShortVersionString` is not correct in `AgoraRtcWrapper` frameworks, cause the user can not submit the APP to the APP Store, which affects the iOS/macOS.
- Update `s.dependency 'AgoraIrisRTC_iOS', '4.2.3-build.4'`
- Update `s.dependency 'AgoraIrisRTC_macOS', '4.2.3-build.4'`
Fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1375
> fix: [iOS/macOS] Fix CFBundleShortVersionString not correct in AgoraRtcWrapper framework

- .github/workflows/build.yml
- .github/workflows/release.yml
Seems that something else in the release_if_merged job is setting up a specific dart environment that isn't compatible. Moved the dartdoc steps to a separate job, which will complete as normal.
The dartdoc job depends on the main `release_if_merged` to complete without errors.
> Separate dartdoc job

- .github/workflows/auto-close-daily-doc-update.yaml
The `stale-pr-label: 'ci:doc'` and `days-before-close: 0` will cause the PR to be closed immediately in every schedule. 
We need to remove the `stale-pr-label: 'ci:doc'` and let the action add the default `Stale` label, see https://github.com/actions/stale#stale-pr-label. Change the `days-before-stale: 1` and `days-before-close: 1`, now the PR will be closed in 2 days if it's stale.
> [ci] Fix the  daily update doc PR had been closed immediately in every schedule

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20231101
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20231101/ios/iris_4.2.3.1-build.4_DCG_iOS_Video_20231101_1049.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20231101/ios/iris_4.2.3.1-build.4_DCG_iOS_Video_20231101_1049_private.zip CDN: https://download.agora.io/sdk/release/iris_4.2.3.1-build.4_DCG_iOS_Video_20231101_1049.zip Cocoapods: pod 'AgoraIrisRTC_iOS', '4.2.3.1-build.4'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20231101/mac/iris_4.2.3.1-build.4_DCG_Mac_Video_20231101_1049.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/E …
```
> feat: upgrade native sdk dependencies 20231101

- .github/workflows/build.yml
- example/ios/Flutter/AppFrameworkInfo.plist
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- example/ios/Runner/Info.plist
The user reports that it's failed to build the example with xcode 15
```
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': CodeSign /Users/joepritchard/Downloads/Agora-Flutter-SDK-main/example/build/ios/Debug-iphoneos/Runner.app
...
```
To fix it, we need to change the order in `Build Phases`. See 
- https://github.com/flutter/flutter/issues/135739
- https://github.com/flutter/flutter/issues/135056#issuecomment-1726407382
I added a new job to cover this case and retained the old `build_ios` job to ensure this change does not affect the user with xcode version < 15.
> [example][ios] Fix build example failed with xcode 15

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20231116
```
implementation 'io.agora.rtc:full-sdk:4.2.6' implementation 'io.agora.rtc:full-screen-sharing:4.2.6' pod 'AgoraRtcEngine_iOS', '4.2.6' pod 'AgoraRtcEngine_macOS', '4.2.6'
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6/20231116/mac/iris_4.2.6-build.3_DCG_Mac_Video_20231116_0243.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6/20231116/mac/iris_4.2.6-build.3_DCG_Mac_Video_20231116_0243_private.zip CDN: https://download.agora.io/sdk/release/iris_4.2.6-build.3_DCG_Mac_Video_20231116_0243.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.2.6-build.3'  Iris: Artifactory: …
```
> feat: upgrade native sdk dependencies 20231116

- example/lib/components/rgba_image.dart
- example/lib/examples/advanced/screen_sharing/screen_sharing.dart
The `DecorderCallback` was deprecated after v2.13.0-1.0.pre, and removed after 3.16.x
```dart
@Deprecated(
'Use ImageDecoderCallback with ImageProvider.loadImage instead. '
'This feature was deprecated after v2.13.0-1.0.pre.',
)
typedef DecoderCallback = Future<ui.Codec> Function(Uint8List buffer, {int? cacheWidth, int? cacheHeight, bool allowUpscaling});
```
But we need to compatible with the Flutter SDK 2.10.x, so we need to avoid directly using the `ImageProvider`
> [example][RgbaImage] Avoid use DecorderCallback which is removed after Flutter SDK 3.16

- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20231207
```
```
```
https://download.agora.io/sdk/release/iris_4.3.0-test.1_DCG_Windows_Video_20231207_0726.zip
```
> feat: upgrade native sdk dependencies 20231207

- android/src/main/cpp/iris_rtc_rendering_android.cc
Clear context current after rendering op to avoid reuse of the same gl context on a different thread, this is a change for the native sdk 4.3.0, the callback thread may be from a different thread after native sdk 4.3.0.
> [android] clear gl context after rendering op

- android/build.gradle
- android/src/main/cpp/third_party/include/iris/iris_base.h
- ios/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
Update native sdk dependencies 20240103
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.231/20240103/android/iris_4.2.6.231-build.2_DCG_Android_Video_20240103_0209.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.231/20240103/android/iris_4.2.6.231-build.2_DCG_Android_Video_20240103_0209_private.zip CDN: https://download.agora.io/sdk/release/iris_4.2.6.231-build.2_DCG_Android_Video_20240103_0209.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.2.6.231-build.2'  Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2.6.231/20240103/ios/iris_4.2.6.231-build.2_DCG_iOS_Video_20240103_0211.zip PrivateArtifactory: …
```
> feat: upgrade native sdk dependencies 20240103

- lib/src/impl/agora_media_engine_impl_override.dart
Wrong call `irisMethodChannel.registerEventHandler` inside `MediaEngineImpl.unregisterAudioFrameObserver`, it should be `irisMethodChannel.unregisterEventHandler`
> fix: Fix MediaEngineImpl.unregisterAudioFrameObserver not unregister eventhandler internally

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240115
```
【三方库链接】 【cdn】 https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_rel.v4.2.6.4_39018_FULL_20240110_2218_289931.zip  【cocoapods】 pod 'AgoraRtcEngine_Special_iOS', '4.2.6.4'    【CDN】  https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_rel.v4.2.6.4_18647_FULL_20240110_0115_289793.zip  【COCOAPODS】  pod 'AgoraRtcEngine_Special_macOS', '4.2.6.4'    【CDN】  https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.4_23440_FULL_20240110_0054_289792.zip https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_rel.v4.2.6.4_56596_FULL_20240110_0059_289790.zip 【maven】 implementation 'io.agora.rtc:full-screen-sharing:4.2.6.4' implementation 'io.agora.rtc:agora-special-full:4.2.6.4' …
```
> feat: upgrade native sdk dependencies 20240115

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240117
```
打包助手 1-17 11:57 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-dev.16'  打包助手 1-17 11:57 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-dev.16'  打包助手 1-17 11:57 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-dev.16'  打包助手 1-17 11:57 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-dev.16'
```
```
打包助手 1-17 12:00 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240117/ios/iris_4.3.0-dev.16_DCG_iOS_Video_20240117_1152.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240117/ios/iris_4.3.0-dev.16_DCG_iOS_Video_20240117_1152_private.zip CDN: …
```
> feat: upgrade native sdk dependencies 20240117

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240122
```
打包助手 1-19 19:21 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.0-dev.18'  打包助手 1-19 19:21 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.0-dev.18'  打包助手 1-19 19:21 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.0-dev.18'  打包助手 1-19 19:22 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.0-dev.18'
```
```
打包助手 1-19 19:10 Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240119/ios/iris_4.3.0-dev.18_DCG_iOS_Video_20240119_0702.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240119/ios/iris_4.3.0-dev.18_DCG_iOS_Video_20240119_0702_private.zip CDN: …
```
> feat: upgrade native sdk dependencies 20240122

- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
Update native sdk dependencies 20240123
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240123/mac/iris_4.3.0-test.2_DCG_Mac_Video_20240123_0527.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240123/mac/iris_4.3.0-test.2_DCG_Mac_Video_20240123_0527_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.0-test.2_DCG_Mac_Video_20240123_0527.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.3.0-test.2'
```
> feat: upgrade native sdk dependencies 20240123

- android/build.gradle
- scripts/artifacts_version.sh
Update native sdk dependencies 20240125
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240125/android/iris_4.3.0-test.8_DCG_Android_Video_20240125_0619.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/littlegnal/20240125/android/iris_4.3.0-test.8_DCG_Android_Video_20240125_0619_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.0-test.8_DCG_Android_Video_20240125_0619.zip Maven: implementation 'io.agora.rtc:iris-rtc:4.3.0-test.8'
```
> feat: upgrade native sdk dependencies 20240125

- lib/src/impl/agora_video_view_impl.dart
- test_shard/integration_test_app/android/build.gradle
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
We get the texture id from the `VideoViewController` that is passed by the user directly, which will be reset if the widget is updated, so we need to maintain it internally.
> fix: [texture rendering] Fix texture id lost when widget is updated

- .github/workflows/build.yml
- ci/run_flutter_integration_test_ios.sh
Fix some ci issues that block the https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1572
- iOS simulator not be created in the rendering test, it is most likely there's no "iPhone 13 Pro Max" in the `macos-12` runner anymore.
- The rendering test for the web failed with Flutter SDK 3.19, will fix it later.
> [ci] Fix some ci issues

- example/ios/Runner/AppDelegate.m
On iOS low power mode, the system force keeps the screen on for 30s only, we keep the screen on to help internal testing.
> [example][ios] Keep screen on

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
Update native sdk dependencies 20240223
```
implementation 'io.agora.rtc:full-sdk:4.3.0' implementation 'io.agora.rtc:full-screen-sharing:4.3.0'  pod 'AgoraRtcEngine_iOS', '4.3.0', pod 'AgoraRtcEngine_macOS', '4.3.0',
```
```
```
> feat: upgrade native sdk dependencies 20240223

- README.md
- example/web/index.html
- scripts/iris_web_version.js
Update native sdk dependencies 20240229
```
```
```
CDN: https://download.agora.io/sdk/release/iris-web-rtc-fake_n430_w4200_0.6.0.js CDN: https://download.agora.io/sdk/release/iris-web-rtc_n430_w4200_0.6.0.js
```
> feat: upgrade native sdk dependencies 20240229

- example/pubspec.yaml
After `agora_rtc_engine: 6.3.0`, we do not implement the `ProcessVideoRawData` example by using the `video_raw_data`.
Fix ci failed https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/8135311600/job/22231749168?pr=1585
> [example] Clean up video_raw_data

- android/src/main/cpp/iris_rtc_rendering_android.cc
- android/src/main/java/io/agora/agora_rtc_ng/VideoViewController.java
- lib/src/impl/platform/io/global_video_view_controller_platform_io.dart
- shared/darwin/VideoViewController.mm
- test_shard/integration_test_app/integration_test/fake/fake_iris_method_channel.dart
- test_shard/integration_test_app/integration_test/testcases/agora_video_view_testcases.dart
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
- windows/include/agora_rtc_engine/video_view_controller.h
- windows/video_view_controller.cc
The `IrisRtcEngineRendering` handle becomes invalid after `RtcEngine.release`, which needs explicit clean-up of the texture renderers on the native side.
Fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1567
> fix: AgoraVideoView crash when dispose after RtcEngine.release

- lib/src/agora_base.dart
- lib/src/agora_media_engine.dart
- lib/src/agora_media_player.dart
- lib/src/agora_rtc_engine.dart
- lib/src/agora_rtc_engine_ex.dart
> [doc] daily update 2024-3-5

- android/build.gradle
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240319
```
打包助手 3-19 19:15 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.6'  打包助手 3-19 19:15 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.6'  打包助手 3-19 19:15 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.6'  打包助手 3-19 19:15 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.6'
```
```
Iris Windows: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240319/windows/iris_4.3.1-dev.6_DCG_Windows_Video_Standalone_20240319_0700_384.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240319/windows/iris_4.3.1-dev.6_DCG_Windows_Video_20240319_0700_384.zip Private: …
```
> feat: upgrade native sdk dependencies 20240319

- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240322
```
```
```
Iris Windows: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240321/windows/iris_4.3.1-dev.7_DCG_Windows_Video_Standalone_20240321_0614_386.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240321/windows/iris_4.3.1-dev.7_DCG_Windows_Video_20240321_0614_386.zip Private: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240321/windows/iris_4.3.1-dev.7_DCG_Windows_Video_20240321_0614_386_private.zip CDN: https://download.agora.io/sdk/release/iris_4.3.1-dev.7_DCG_Windows_Video_Standalone_20240321_0614_386.zip https://download.agora.io/sdk/release/iris_4.3.1-dev.7_DCG_Windows_Video_20240321_0614_386.zip
```
> This …
> feat: upgrade native sdk dependencies 20240322

- pubspec.yaml
This PR fixes #1657 by tweaking the `pubspec.yaml` file.
Once this change is implemented, developers who use this plugin won't be prevented from using new linting features.
> Allow newer `flutter_lints` versions

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240409
```
implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.12' implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.12' pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.12' pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.12'
```
```
https://download.agora.io/sdk/release/iris_4.3.1-dev14_DCG_Android_Video_20240409_0607_467.zip https://download.agora.io/sdk/release/iris_4.3.1-dev14_DCG_iOS_Video_20240409_0607_376.zip https://download.agora.io/sdk/release/iris_4.3.1-dev14_DCG_Mac_Video_20240409_0607_375.zip https://download.agora.io/sdk/release/iris_4.3.1-dev14_DCG_Windows_Video_20240409_0607_409.zip implementation 'io.agora.rtc:iris-rtc:4.3.1-dev14' pod 'AgoraIrisRTC_iOS', '4.3.1-dev14' pod …
```
> feat: upgrade native sdk dependencies 20240409

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240410
```
打包助手 4-10 12:16 Packages: implementation 'io.agora.rtc:agora-full-preview:4.3.1-dev.15'  打包助手 4-10 12:16 Packages: implementation 'io.agora.rtc:full-screen-sharing-special:4.3.1-dev.15'  打包助手 4-10 12:16 Packages: pod 'AgoraRtcEngine_macOS_Preview', '4.3.1-dev.15'  打包助手 4-10 12:17 Packages: pod 'AgoraRtcEngine_iOS_Preview', '4.3.1-dev.15'  打包助手 4-10 12:17 CDN: https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_4.3.1-dev.15.zip  打包助手 4-10 12:17 CDN: https://download.agora.io/sdk/release/AgoraRtcEngine_macOS_Preview_4.3.1-dev.15.zip
```
```
打包助手 4-10 12:08 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240410/ios/iris_4.3.1-dev.15_DCG_iOS_Vid …
```
> feat: upgrade native sdk dependencies 20240410

- scripts/iris_web_version.js
Update native sdk dependencies 20240411
```
```
```
https://download.agora.io/sdk/release/iris-web-rtc-fake_n430_w4200_0.7.0-pre.js
```
> feat: upgrade native sdk dependencies 20240411

- README.md
- example/web/index.html
- scripts/iris_web_version.js
Update native sdk dependencies 20240415
```
```
```
CDN: https://download.agora.io/sdk/release/iris-web-rtc_n430_w4200_0.7.0-pre.js
```
> feat: upgrade native sdk dependencies 20240415

- lib/src/impl/agora_rtc_engine_impl.dart
- pubspec.yaml
- test_shard/integration_test_app/integration_test/fake/fake_iris_method_channel.dart
- test_shard/integration_test_app/integration_test/fake_apis_call_integration_test.dart
- test_shard/integration_test_app/integration_test/testcases/mediarecorder_fake_test_testcases.dart
- test_shard/integration_test_app/integration_test/testcases/rtcengine_fake_test_testcases.dart
A case like:
```dart
for (int i = 0; i < 5; ++i) {
rtcEngine.initialize(RtcEngineContext(
appId: engineAppId,
areaCode: AreaCode.areaCodeGlob.value(),
logConfig: LogConfig(filePath: logPath),
));
}
```
This causes `irisMethodChannel.initilize(args)`, and `_initializeInternal(context)` called multiple times, which causes unexpected behaviors.
`iris_method_channel` fix: https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/98
> fix: Prevent multiple initializations of internal resources when `RtcEngine.initialize` is called simultaneously

- README.md
- example/web/index.html
- scripts/iris_web_version.js
Update native sdk dependencies 20240508
```
```
```
CDN: https://download.agora.io/sdk/release/iris-web-rtc-fake_n430_w4200_0.7.0.js CDN: https://download.agora.io/sdk/release/iris-web-rtc_n430_w4200_0.7.0.js
```
> feat: upgrade native sdk dependencies 20240508

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- pubspec.yaml
Update native sdk 6.1.1-ps.411191 dependencies
> feat: upgrade native sdk 6.1.1-ps.411191

- .gitignore
- ci/run_flutter_integration_test.sh
- ci/run_rendering_test.sh
- test_shard/fake_test_app/lib/main.dart
- test_shard/fake_test_app/pubspec.yaml
- test_shard/fake_test_app/web/index.html
- test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
- test_shard/integration_test_app/lib/fake_remote_user_main.dart
- test_shard/integration_test_app/lib/main.dart
- test_shard/rendering_test/lib/main.dart
- test_shard/rendering_test/pubspec.yaml
- test_shard/rendering_test/web/index.html
Some tests failed after upgrading the Flutter SDK 3.22, see https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/9177683376/job/25235867951?pr=1774
- Remove the use of `Theme.of(context).textTheme.headline4`.
- We previously added the `iris_web_version.js` as assets, and let the Flutter SDK copy the `iris_web_version.js` to the web folder, which does not work on Windows with Flutter SDK 3.22. We now copy the `iris_web_version.js` before running the test explicitly.
- The method channel call of `destroyTextureRender ` does not be mocked
- Remove the `FakeMethodChannelController.dispose`, which may reset the mock `MethodChannelCallHandler` too early, which caused an error on Windows(We checked the texture id can not be 0 on Windows).
> [test_shard] Fix some tests failed after upgrading the Flutter SDK 3.22

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240529
```
```
```
打包助手 5-29 18:58 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240529/ios/iris_4.3.2-dev.4_DCG_iOS_Video_Standalone_20240529_0651_405.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240529/ios/iris_4.3.2-dev.4_DCG_iOS_Video_20240529_0651_405.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240529/ios/iris_4.3.2-dev.4_DCG_iOS_Video_20240529_0651_405_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.3.2-dev.4_DCG_iOS_Video_Standalone_20240529_0651_405.zip https://download.agora.io/sdk/release/iris_4.3.2-dev.4_DCG_iOS_Video_20240529_0651_405.zip Cocoapods: pod …
```
> feat: upgrade native sdk dependencies 20240529

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240531
```
```
```
打包助手 5-31 11:24 Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.5_DCG_iOS_Video_Standalone_20240531_1116_406.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.5_DCG_iOS_Video_20240531_1116_406.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240531/ios/iris_4.3.2-dev.5_DCG_iOS_Video_20240531_1116_406_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.3.2-dev.5_DCG_iOS_Video_Standalone_20240531_1116_406.zip https://download.agora.io/sdk/release/iris_4.3.2-dev.5_DCG_iOS_Video_20240531_1116_406.zip Cocoapods: pod …
```
> feat: upgrade native sdk dependencies 20240531

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240605
```
implementation 'io.agora.rtc:full-sdk:4.3.2' implementation 'io.agora.rtc:full-screen-sharing:4.3.2'  pod 'AgoraRtcEngine_iOS', '4.3.2' pod 'AgoraRtcEngine_macOS', '4.3.2'
```
```
Iris macOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_20240604_0500_404.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_Standalone_20240604_0500_404.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_20240604_0500_404_private.zip  CDN: …
```
> feat: upgrade native sdk dependencies 20240605

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240606
```
implementation 'io.agora.rtc:full-sdk:4.3.2' implementation 'io.agora.rtc:full-screen-sharing:4.3.2'  pod 'AgoraRtcEngine_iOS', '4.3.2' pod 'AgoraRtcEngine_macOS', '4.3.2'
```
```
Iris macOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_20240604_0500_404.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_Standalone_20240604_0500_404.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.3/20240604/mac/iris_4.3.2-build.1_DCG_Mac_Video_20240604_0500_404_private.zip  CDN: …
```
> feat: upgrade native sdk dependencies 20240606

- tool/terra/build.sh
The code only matches the 3-segment version, but the native SDK can be 2-segment or 4-segment.
> [ci][code-gen.yaml] Fix version regex

- internal/deps_summary.txt
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240607
```
```
```
Iris: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2.142-build.1/iris_4.2.2.142-build.1_DCG_Windows_Video_20240329_1152.zip Symbol: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/IRIS_RELEASE/4.2.2.142-build.1/iris_4.2.2.142-build.1_DCG_Windows_Video_20240329_1152_symbols.zip CDN: https://download.agora.io/sdk/release/iris_4.2.2.142-build.1_DCG_Windows_Video_20240329_1152.zip
```
> feat: upgrade native sdk dependencies 20240607

- lib/src/impl/json_converters.dart
- test/json_converters_test.dart
- tool/terra/renderers/utils.ts
The native side will return a 64-bits int ptr value, most of it is `view_t`, `void *`, which will cause the dart `jsonDecode` error, so we passed the int ptr value through the string, and parse it to the int value.
This change is not yet supported on iris 4.3.x, so we do not apply any code changes at this time.
> Fix can not parse 64-bits int from JSON

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
Update native sdk dependencies 20240612
```
【maven】 implementation 'io.agora.rtc:agora-special-full:4.2.6.240'  implementation 'io.agora.rtc:full-screen-sharing:4.2.6.240'  【cocoapods】 pod 'AgoraRtcEngine_Special_iOS', '4.2.6.240'
```
```
```
> feat: upgrade native sdk dependencies 20240612

- example/lib/main.dart
Add global error handling to log errors to the `logSink`, which helps internal testing.
> [example] Log errors to the logSink

- ci/run_flutter_integration_test_android.sh
- example/android/app/build.gradle
- example/android/build.gradle
- test_shard/fake_test_app/android/build.gradle
- test_shard/integration_test_app/android/app/build.gradle
- test_shard/integration_test_app/android/build.gradle
- test_shard/iris_tester/android/build.gradle
- test_shard/iris_tester/example/android/build.gradle
- test_shard/rendering_test/android/build.gradle
> Error: Your project's Kotlin version (1.6.10) is lower than Flutter's minimum supported version of 1.7.0. Please upgrade your Kotlin version. 
Alternatively, use the flag "--android-skip-build-dependency-validation" to bypass this check.
Fix build failed with Flutter SDK 3.24, which needs minimum Kotlin version 1.7.0 
Failed job: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/10305485073/job/28526448084?pr=1943
> Bump minimum kotlin version to 1.7.0

- android/build.gradle
- internal/deps_summary.txt
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native sdk dependencies 20240815
```
```
```
打包助手 8-15 11:51 Iris Android: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240815/android/iris_4.2.6.16-build.1_DCG_Android_Video_Standalone_20240815_1139.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240815/android/iris_4.2.6.16-build.1_DCG_Android_Video_20240815_1139.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.2/20240815/android/iris_4.2.6.16-build.1_DCG_Android_Video_20240815_1139_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.2.6.16-build.1_DCG_Android_Video_Standalone_20240815_1139.zip https://download.agora.io/sdk/release/iris_4.2.6.16-build.1_DCG_Android_Video …
```
> feat: upgrade native sdk dependencies 20240815

- android/build.gradle
- ci/run_flutter_integration_test_android.sh
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/main/kotlin/io/agora/agora_rtc_flutter_example/ExampleService.kt
- example/android/app/src/main/kotlin/io/agora/agora_rtc_flutter_example/MyApplication.kt
- example/android/build.gradle
- example/lib/main.dart
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- pubspec.yaml
- test_shard/fake_test_app/android/build.gradle
- test_shard/integration_test_app/android/app/build.gradle
- test_shard/integration_test_app/android/build.gradle
- test_shard/iris_tester/android/build.gradle
- test_shard/iris_tester/example/android/build.gradle
- test_shard/rendering_test/android/build.gradle
Update native sdk 4.3.1.139.hw dependencies
> feat: upgrade native sdk 4.3.1.139.hw

- tool/testcase_gen/pubspec.yaml
The main branch will support the dart records features, which require the dart SDK >= 3.0.0, so we pin the `paraphrase` to avoid a break change.
https://github.com/littleGnAl/paraphrase/pull/1
> [testcase_gen] Pin paraphrase to tag: 0.1.0

- .github/workflows/build.yml
We need this change(https://github.com/flutter/engine/commit/90815e5f75dee1c20ce6d61d5161157513d90b84), which was released in Flutter SDK 3.7.0 to fix a crash on Windows(https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1999)
This PR is preparing for the fix.
> feat: Bump minimum supported Flutter SDK >= 3.7.0

- .github/workflows/build.yml
We want the job to keep running although the other job has failed in the `matrix`.
Refer https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> [ci][build] Set fail-fast: false for the matrix run

- example/lib/examples/advanced/screen_sharing/screen_sharing.dart
Pick some example changes from the special version.
> [example] Pick some example changes that help internal testing

- pubspec.yaml
Upgrade iris_method_channel to version ^2.2.0 to ensure compatibility with the 2.x.
> Upgrade iris_method_channel: ^2.2.0

- shared/darwin/TextureRenderer.mm
- windows/texture_render.cc
[texture rendering][macos/ios/windows] Update the frame position to POSITION_POST_CAPTURER | POSITION_PRE_RENDERER for consistency with the Android changes introduced in version 4.3.2. Without this update, a bug will occur in version 4.4.0. This change also prepares for further adjustments in 4.4.0.
> [texture rendering][macos/ios/windows] Update the frame position to POSITION_POST_CAPTURER | POSITION_PRE_RENDERER

- lib/src/agora_rtc_engine.dart
- lib/src/binding/agora_rtc_engine_event_impl.dart
- lib/src/binding/event_handler_param_json.dart
- lib/src/binding/event_handler_param_json.g.dart
- test_shard/fake_test_app/integration_test/generated/event_ids_mapping_gen.dart
- test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
- test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
- tool/terra/configs/cud_node_parser.config.ts
Fix `onFirstLocalVideoFramePublished` not fired, the one with `connection` is fired by Native SDK.
Fix `onLocalVideoStats` not fired, the one with `connection` is fired by Native SDK.
> fix: Fix some callbacks not fired

- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
Update native dependencies 20240929
```
Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20240929/ios/iris_4.5.0-dev.5_DCG_iOS_Video_20240929_0602_538.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20240929/ios/iris_4.5.0-dev.5_DCG_iOS_Video_Standalone_20240929_0602_538.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20240929/ios/iris_4.5.0-dev.5_DCG_iOS_Video_20240929_0602_538_xdump.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20240929/ios/iris_4.5.0-dev.5_DCG_iOS_Video_20240929_0602_538_private.zip  CDN: https://download.agora.io/sdk/release/iris_4.5.0-dev.5_DCG_iOS_Video_20240929_0602_538.zip …
```
> feat: upgrade native sdk dependencies 20240929

- .github/workflows/build.yml
- android/src/main/cpp/CMakeLists.txt
- scripts/check_android15_16k_page_alignment.sh
Close https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/2041
> fix: support android 15 16k page size

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native dependencies 20241015
```
打包助手 10-11 13:40 Iris macOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241011/mac/iris_4.5.0-dev.6_DCG_Mac_Video_20241011_0131_511.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241011/mac/iris_4.5.0-dev.6_DCG_Mac_Video_Standalone_20241011_0131_511.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241011/mac/iris_4.5.0-dev.6_DCG_Mac_Video_20241011_0131_511_private.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241011/mac/iris_4.5.0-dev.6_DCG_Mac_Video_20241011_0131_511_xdump.zip  CDN: https://download.agora.io/sdk/release/iris_4.5.0-dev.6_DCG_Mac_Video_20241011_0131_511.zip …
```
> feat: upgrade native sdk dependencies 20241015

- android/consumer-rules.pro
Suppress `ERROR: R8: Missing class com.google.devtools.build.android.desugar.runtime.ThrowableExtension` when running with AGP 8.x
The Android Native SDK has caught this error internally, so we're safe to suppress this error.
Fix failed job https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/11359234733/job/31595029855?pr=2049
> fix: Suppress R8 missing class com.google.devtools.*.ThrowableExtension for AGP 8.x

- .github/workflows/build.yml
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
Cover the customer's scenario https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1832#issuecomment-2397237341
> [example][android] Bump AGP 8.7 and Gradle 8.10

- android/src/main/java/io/agora/agora_rtc_ng/VideoViewController.java
- example/ios/Flutter/AppFrameworkInfo.plist
- example/ios/Podfile
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- example/ios/Runner/AppDelegate.swift
- ios/Classes/AgoraRtcNgPlugin.m
- shared/darwin/TextureRenderer.mm
- shared/darwin/VideoViewController.h
- shared/darwin/VideoViewController.mm
If an `AgoraVideoView` is displayed and a video frame callback is received while the app is quitting, there is a potential crash risk due to access to invalid resources(invalid adresses) in the callback. To prevent this, we should ensure that resources are properly cleaned up in the destructor.
This logic is already handled in the Windows implementation, so in this PR, we are updating it for Android, iOS, and macOS only.
> fix: Fix a potential crash in AgoraVideoView when the app is force quit

- pubspec.yaml
See https://github.com/AgoraIO-Extensions/Agora-Flutter-RTM-SDK/pull/181
> Update iris_method_channel constraint to >= 2.2.2 for improved compatibility

- android/build.gradle
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/c/c_player.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_callback_utils.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_canvas.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_error.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_player.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_rte.h
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native dependencies 20241106
```
Iris iOS: Artifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241106/ios/iris_4.5.0-dev.12_DCG_iOS_Video_Standalone_20241106_1156_555.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241106/ios/iris_4.5.0-dev.12_DCG_iOS_Video_20241106_1156_555.zip PrivateArtifactory: https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241106/ios/iris_4.5.0-dev.12_DCG_iOS_Video_20241106_1156_555_private.zip https://artifactory-api.bj2.agoralab.co/artifactory/CSDC_repo/EP/4.5/20241106/ios/iris_4.5.0-dev.12_DCG_iOS_Video_20241106_1156_555_xdump.zip  CDN: https://download.agora.io/sdk/release/iris_4.5.0-dev.12_DCG_iOS_Video_Standalone_20241106_1156_555.zip …
```
> feat: upgrade native sdk dependencies 20241106

- README.md
- android/build.gradle
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/c/c_rte.h
- android/src/main/cpp/third_party/include/agora_rtc/rte_base/rte_cpp_rte.h
- example/web/index.html
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- scripts/iris_web_version.js
Update native dependencies 20241125
```
CDN: https://download.agora.io/sdk/release/iris-web-rtc-fake_n440_w4220_0.8.4.js CDN: https://download.agora.io/sdk/release/iris-web-rtc_n440_w4220_0.8.4.js CDN: https://download.agora.io/sdk/release/iris_4.5.0-dev.15_DCG_Mac_Video_20241125_1201_533.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.5.0-dev.15' https://download.agora.io/sdk/release/iris_4.5.0-dev.15_DCG_Windows_Video_Standalone_20241125_1202_576.zip implementation 'io.agora.rtc:iris-rtc:4.5.0-dev.15' https://download.agora.io/sdk/release/iris_4.5.0-dev.15_DCG_Android_Video_16K_20241125_1201_699.zip pod 'AgoraIrisRTC_iOS', '4.5.0-dev.15' https://download.agora.io/sdk/release/iris_4.5.0-dev.15_DCG_iOS_Video_20241125_1201_573.zip pod 'AgoraRtcEngine_iOS_Preview', …
```
> feat: upgrade native sdk dependencies 20241125

- android/build.gradle
- internal/deps_summary.txt
- ios/agora_rtc_engine.podspec
- macos/agora_rtc_engine.podspec
- scripts/artifacts_version.sh
- windows/CMakeLists.txt
Update native dependencies 20241203
```
CDN: https://download.agora.io/sdk/release/iris-web-rtc-fake_n440_w4220_0.8.4.js CDN: https://download.agora.io/sdk/release/iris-web-rtc_n440_w4220_0.8.4.js https://download.agora.io/sdk/release/iris_4.5.0-build.1_DCG_Mac_Video_20241203_0322_534.zip https://download.agora.io/sdk/release/iris_4.5.0-build.1_DCG_Windows_Video_20241203_0322_577.zip Cocoapods: pod 'AgoraIrisRTC_macOS', '4.5.0-build.1' implementation 'io.agora.rtc:iris-rtc:4.5.0-build.1' https://download.agora.io/sdk/release/iris_4.5.0-build.1_DCG_Android_Video_16K_20241203_0322_701.zip pod 'AgoraIrisRTC_iOS', '4.5.0-build.1' https://download.agora.io/sdk/release/iris_4.5.0-build.1_DCG_iOS_Video_20241203_0325_575.zip pod 'AgoraRtcEngine_iOS', '4.5.0' pod …
```
> feat: upgrade native sdk dependencies 20241203

- .github/workflows/build.yml
- .github/workflows/integration-test-iris-artifacts.yml
- .github/workflows/schedule-run-ci-external.yml
- .github/workflows/schedule-run-ci-internal.yml
This reverts commit 6ff4ffdaecad811c529c64025dd756b106f07862.
> Revert "chore: limit timeout from 120 or 60 mins to 30 mins"

- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
- .github/workflows/release_special_version.yml
See
https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/pull/111
> [ci] Fix CI failed caused by using an unsupported NodeJS version (#2070)

- lib/src/_serializable.dart
- lib/src/agora_base.dart
- lib/src/agora_log.dart
- lib/src/agora_media_base.dart
- lib/src/agora_media_player_types.dart
- lib/src/agora_media_streaming_source.dart
- lib/src/agora_music_content_center.dart
- lib/src/agora_rhythm_player.dart
- lib/src/agora_rtc_engine.dart
- lib/src/agora_rtc_engine_ex.dart
- lib/src/agora_spatial_audio.dart
- lib/src/binding/call_api_impl_params_json.dart
- lib/src/binding/event_handler_param_json.dart
- lib/src/impl/agora_music_content_center_impl_json.dart
- lib/src/impl/json_converters.dart
...so class instances will be shown as `Type(a: xx, b: yy)` instead of `Instance 'Type'` when parsed by readables (e.g. console).
> ⚡️ Make data classes serializable

- lib/src/_serializable.dart
- lib/src/agora_base.dart
- lib/src/agora_h265_transcoder.dart
- lib/src/agora_log.dart
- lib/src/agora_media_base.dart
- lib/src/agora_media_engine.dart
- lib/src/agora_media_player.dart
- lib/src/agora_media_player_source.dart
- lib/src/agora_media_player_types.dart
- lib/src/agora_media_recorder.dart
- lib/src/agora_media_streaming_source.dart
- lib/src/agora_music_content_center.dart
- lib/src/agora_rhythm_player.dart
- lib/src/agora_rtc_engine.dart
- lib/src/agora_rtc_engine_ex.dart
- lib/src/agora_spatial_audio.dart
- lib/src/audio_device_manager.dart
- lib/src/binding/call_api_impl_params_json.dart
- lib/src/binding/event_handler_param_json.dart
- lib/src/impl/agora_music_content_center_impl_json.dart
- lib/src/impl/json_converters.dart
- tool/terra/renderers/api_interface_renderer.ts
- tool/terra/renderers/callapi_impl_renderer.ts
- tool/terra/renderers/event_handler_impl_params_json_renderer.ts
- tool/terra/renderers/utils.ts
...so class instances will be shown as `Type(a: xx, b: yy)` instead of `Instance 'Type'` when parsed by readables (e.g. console).
> feat: make data classes serializable (#2223)

- lib/src/impl/platform/web/global_video_view_controller_platform_web.dart
The ui.platformViewRegistry (currently deprecated) will be removed on the next flutter stable release.
Which throws:
`Error: Undefined name 'platformViewRegistry'.`
The solution is to use `dart:ui_web` instead of `dart:ui`, both available in flutter.
> fix: Undefined name 'platformViewRegistry'.

- lib/src/impl/platform/web/global_video_view_controller_platform_web.dart
revert AgoraIO-Extensions/Agora-Flutter-SDK#2273
@arthurbcd 
I've investigated the test failures and discovered a complex situation:
- Initially, when running tests on the external PR, only the base branch was checked out (not including the commit in question: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/14608607680/job/40982332098). This led to a false positive in our test results.
- Further testing revealed multiple test failures on the main branch. To address this, I attempted to:
- First, pin the minimum Flutter SDK version to 3.13.0 (which includes the ui-web fix https://github.com/flutter/engine/commit/f37e78ca2d089e62924b9141887965bfa1204e8e)
- However, this still resulted in numerous test failures
- Given these issues, I've decided to:
- Revert the …
> revert: "fix: Undefined name 'platformViewRegistry'."

- android/src/main/cpp/iris_rtc_rendering_android.cc
https://developer.android.com/reference/android/graphics/SurfaceTexture#setDefaultBufferSize(int,%20int)
> For OpenGL ES, the EGLSurface should be destroyed (via eglDestroySurface), made not-current (via eglMakeCurrent), and then recreated (via eglCreateWindowSurface) to ensure that the new default size has taken effect.
https://blog.csdn.net/wzw88486969/article/details/138485679
> fix: eliminate video playback flicker during resolution changes
